name: Backend CI/CD

on:
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          
      - name: Test Backend Services
        run: |
          cd backend/addToCart && ./mvnw test && cd ../..
          cd backend/productdetailsservice && ./mvnw test && cd ../..
          cd backend/usermetadata && ./mvnw test && cd ../..
          
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Deploy
        run: |
          cd backend/addToCart
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-addtocart:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-addtocart:latest
          cd ../productdetailsservice
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-productdetails:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-productdetails:latest
          cd ../usermetadata
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-usermetadata:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-usermetadata:latest
