name: Backend CI/CD to Render

on:
  push:
    branches:
      - main
      - deploy-setup
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push AddToCart Service
        run: |
          cd backend/addToCart
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-addtocart:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-addtocart:latest
          cd ../..

      - name: Build and Push ProductDetails Service
        run: |
          cd backend/productdetailsservice
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-productdetails:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-productdetails:latest
          cd ../..

      - name: Build and Push UserMetadata Service
        run: |
          cd backend/usermetadata
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-usermetadata:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-usermetadata:latest
          cd ../..

      - name: Deployment notification
        run: |
          echo "All microservices built and pushed to Docker Hub successfully!"
          echo "Render will automatically detect and deploy the new images"
